name: Cookislands
favicon: null
layout_spectrum: 0.7410550795029849
typography_spectrum: 0.038124619983136654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4435635101981461
  lightness: 0.3565237168222666
  saturation: 0.20659233769401908
  rhythmicContrast: 0.8931606223341078
purpose: []
